### ISSUE TITLE
setup.py file missing?

### ISSUE THREAD

**Issue by nlwagner** [jrenaud90/TidalPy#45]
Title explains it. I've both cloned the repository and downloaded the repository as a zip file and I can't find the setup.py file. I've searched in every directory within TidalPy and made sure setuptools was installed. I think I might be missing something obvious, but until it's revealed to me I'm still very unsure where it might be.

I created a new conda environment to run this all under. A summary of commands run thus far are:

> conda create -n tidalpy python=3.9
> conda activate tidalpy
> git clone https://github.com/jrenaud90/TidalPy.git
>  cd TidalPy

I feel embarrassed opening up this issue because it's so simple but any help is appreciated.

**Comment by jrenaud90** [comment]
Hey @nlwagner! 

No need to be embarrassed, it is quite odd but having no `setup.py` was actually done intentionally. It complies with the revamp to packages started with PEPs [518](https://peps.python.org/pep-0518/) and [621](https://peps.python.org/pep-0621/), as well as changes to setuptools. These changes actually remove the need for a setup.py for purely python packages. 

However, all of this is a moot point: the newest version of TidalPy (v0.5.0; introduced by PR #46) returns setup.py as TidalPy now needs to compile C files and this is not well supported by a pure pyproject.toml approach.

When v0.5.0 goes live (on 2024-02-14; so hopefully now as you read this depending on your timezone and any last minute issues), I highly recommend using it. I also recommend installing TidalPy from pip rather than from the repo itself. Pip will, hopefully, find a prebuilt wheel that matches your environment requirements and save you a lot of hassle dealing with compile issues.

```python
python -m pip install "TidalPy>=0.5.0"
```

Let me know if this helps!

**Comment by jrenaud90** [comment]
Great! Let me know if you run into any other issues.
